### ISSUE TITLE
Generated Windows executable doesn't run successfully with Node 10 target

### ISSUE THREAD

**Issue by alzadude** [vercel/pkg#779]
**Given**
Project: https://github.com/digital-dj-tools/mp3-parser
pkg version: 4.4.0
pkg targets: node10-win-x64,node10-macos-x64,node10-linux-x64
```
npm install
clojure -Acompile-cljs
npm run build
```
**Expected**
The Windows and Linux generated executables run ok (I can't test the Macos executable, I don't have a Mac).

**Actual**
The Linux executable runs successfully, but the Windows executable does not.

From Bash (WSL)
```
/mnt/d/Projects/mp3-parser/pkg$ ./mp3-parser-linux ./test-resources/lame-mp3-cbr-stereo-44100khz-192kbps-id3v2.mp3
<generates correct output>
```
From CMD (Windows)
```
D:\Projects\mp3-parser\pkg>mp3-parser-win.exe ..\test-resources\lame-mp3-cbr-stereo-44100khz-192kbps-id3v2.mp3
<no output>
D:\Projects\mp3-parser\pkg>echo %errorlevel%
-1073741819
```
However, if I change targets to node8-win-x64,node8-macos-x64,node8-linux-x64, the Windows and Linux generated executables run ok.

Why do some of the generated executables (Windows) not run successfully with Node 10?

**Comment by chrisbednarski** [comment]
I'm seeing the same issue when targetting `node10-win-x86`

When running an exe packaged with 4.4.0 I see an error
`Pkg: Error reading from file`

It works correctly when packaged with 4.3.8

**Comment by rao123dk** [comment]
Yes, there is a compatibility issue with node@10 and pkg@4.4.0. It will work with pkg@4.3.7 or pkg@4.3.8.

**Comment by gabrielstuff** [comment]
I confirm, that using pkg@4.4.0 will fail to produce an exe for windows 10. Using same config and module with pkg@4.3.8 works.

thanks @rao123dk

**Comment by Fadoli** [comment]
Same for newer 4.4.x releases

**Comment by Danita** [comment]
I can confirm I could successfully compile a Mac target from Windows using pkg@4.3.8

**Comment by saostad** [comment]
I had exact same problem and it solved with command below:
```
pkg ./dist/index.js --target node12-win-x64 --options max_old_space_size=4096
```

**Comment by albertmourato** [comment]
I faced the same problem!

**Comment by jaredgorski** [comment]
Looks like this error happens in the `need()` function from `pkg-fetch` used in `lib/index.js` in this repo. Looking at `pkg-fetch`, the error is thrown when it doesn't find a matching version from this `patches.json` file (https://github.com/vercel/pkg-fetch/blob/b80b344757ea9b8c93ce9353dd57fa70bf8c67f0/patches/patches.json).

Try using a version from `patches.json` and it should work

**Comment by Nashorn** [comment]
still an issue, tried 4.3.x with node10 on win, no combinations working. Exe opens and exists immediately.

**Comment by albertmourato** [comment]
@Nashorn check [this file](https://github.com/vercel/pkg-fetch/blob/master/patches/patches.json). You should use one of them in order to get it working.

**Comment by Nashorn** [comment]
@albertmourato thanks for your help. I've tried a number of diff combinations, can't say I tried them all on that list. At this point its trial and error (windows only), the thing works flawlessly on mac/linux.

Let me share my config and small example, maybe i have it configured wrong? Basically making a self-executing server (using the npm http-server module) that launches a localhost from the folder it is opened from. Works perfect like i said on macos/linux, just not on Windows, even with various targets and diff versions of PKG. CMD window opens to black screen and closes immediately.

When i cd into folder an open the .exe, i see my logs fine, no errors, and cmd stays open. No idea at this point. Any help appreciated:

```
{
    "name": "pkgtest",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "author": "test",
    "scripts": {
        "start": "http-server ./ -o index.html"
    },
    "bin": "$DIR/node_modules/http-server/bin/http-server",
    "dependencies": {
        "http-server": "^0.12.3"
    },
    "assets": [
        "./node_modules/*",
        "./node_modules/http-server"
    ]
}
```

And index.js:
```
var http_server = require("http-server");
var path = require("path");
const cwd = process.cwd();
var exec = require('child_process').exec;
var s = process.execPath;
    s = s.substr(0,s.lastIndexOf("/"));


    console.log("app path",s);//not used
    console.log("process.execPath",path.dirname(process.execPath));
    console.log("process.cwd",process.cwd());
    console.log("process.pkg",process.pkg);
    console.log("process.versions",process.versions)
    if(http_server){
        console.log("http_server", "successs");
    }else{
        console.log("http_server", "Server module not found")
    } 
    process.chdir(path.dirname(process.execPath));
    console.log("changed dir to",process.cwd());
    console.log("Starting npm");
    exec("npm start")
    process.exit();
```

**Comment by Nashorn** [comment]
any help on this?

**Comment by Nashorn** [comment]
its a dead simple example, no one from pkg team knows?
